### ISSUE TITLE
PlutoStaticHTML, global scope and CI

### ISSUE THREAD

**Issue by kellertuer** [rikhuijzer/PlutoStaticHTML.jl#158] opened 2023-01-06 13:13 UTC
I am fighting again some reproducibility issues with PlutoStaticHTML.

I know we discussed something similar before, but I have a specific issue currently with breaking changes.

Usually with the new Package manager versions are fixed. But that would mean I can only update tutorials in a version _after_ that is registered. So I switched for now to use `Pkg.activate()` to deactivate the package manager again. That works very fine locally and it uses the new version (with the breaking changes) to generate the new tutorials locally.

However on CI something very strange is happening. See

https://github.com/JuliaManifolds/Manopt.jl/actions/runs/3854665576/jobs/6568897513#step:4:412

the package Manopt is installed (to be safe I even added it to the dependencies in the project.toml, which should not be necessary). However, while the local run of Documenter is fine and generates the PlutoStaticHTML notebooks, on CI I get

https://github.com/JuliaManifolds/Manopt.jl/actions/runs/3854665576/jobs/6568897513#step:4:927

so it seems that (just on CI!) it does a local scope for the notebook without any packages? Both the CI and my local run are on PlutoStaticHTML 6.0.8.

Any clue what that might be?

**Comment by kellertuer** [comment] 2023-01-06 14:37
Oh and just for reference, on the “I have to register a version before updating tutorials” I opened a discussion at https://github.com/fonsp/Pluto.jl/discussions/2432, since I thought about all this quite a while and I think that is a not-that-easy thing overall – and for now using the global Pkg at least on breaking releases is a temporary fix :)

**Comment by rikhuijzer** [comment] 2023-01-06 15:04
Okay, so for future reference, you seem to be working on https://github.com/JuliaManifolds/Manopt.jl/pull/174.

The issue is not very strange actually. In `[tutorials/Optimize!.jl](https://github.com/JuliaManifolds/Manopt.jl/pull/174/files#diff-9d99f1f4945ea3e9e21abe574a7c9a4e4e924b8f1d49913bf09f23baa74646da)`, you've added a cell containing:
```julia
using Pkg
```
This disables the Pluto package manager. Next, `using Foo` where `Foo` is not a standard library will fail because they are not installed.

I would advice to change the `using Pkg` block to something like the following:

```julia
# hideall
begin
    using Pkg
    Pkg.activate(; temp=true)
    packages = [
        PackageSpec(; name="Manopt", version="0.3"),
        PackageSpec(; name="CairoMakie", version="0.7"),
        PackageSpec(; name="CSV", version="0.10"),
        [...]
    ]
    Pkg.add(packages)
end
```
and, yes, this is verbose, but it is also rock-solid. There is not much hidden about the version numbers and you have complete control over what version to use.

Also, are you sure, that `previous_dir=tutorial_output_folder` in `docs/make.jl` is what you want? The cache should always be a miss in your situation because `Manopt.jl` is always changing, right?

Closing this issue since this behavior is expected.

**Closed by rikhuijzer** 2023-01-06 15:04 UTC

**Comment by kellertuer** [comment] 2023-01-06 15:15
Sorry, sure, I should have mentioned the PR.

May I ask for a clarification?
Why do I have to add the Packages again in Pkg when I am running on CI? Locally it takes my 1.8-Environment and all is fine, why does it not take the CI environment (like everything else in the Documenter does on CI)?
So _why_ is that not installed? It _is_ installed on CI and documenter also uses the 0.4.0 (new version) when generating the docs – so why does PlutoStaticHTML not take the same environment it is called from (from within make.jl)?

And even more – why _does_ it do that locally? Since on my machine I do not need this humungous large block of ugly code. Especially I do not want Manopt 0.3 but the (not yet registered) 0.4 from the PR.

Sorry for asking so many questions, but I seem to miss something important here, since I do completely not understand why that is as expected - especially since all this runs fine locally but not on CI.

---

For the cache – I do not yet have completely understood how that should work, for now I was just happy that it locally reduced the time to generate the docs, since the tutorials take 4 minutes to run.
I might check to do that on CI later but I am ok with misses for now. I was even surprised that it worked at all for now.

**Comment by kellertuer** [comment] 2023-01-06 15:49
Yes, sorry for the not-so-nice tone – that problem just “stole” my last night. But that is of course not your fault.

But the notebooks also run locally if I delete the cache and run them again. Hm.

And sure in general all the reproducibility is one of my favourite things of Pluto – just that for exactly this case of updating tutorials to a next version (either including breaking changes or new features one wants to illustrate), this reproducibility is a little tricky.

With the docs directory I am not yet so sure it will work, at least not consistently between local and CI for a simple reason:
The docs-project.toml will not have Manopt in its dependencies (it never had) and locally here that would mean I would have to ask somewhere for the `dev` version? I will have to check for that.
But I also do not remember why I activated “use_distributed”, because PlutoStaticHTML – at least for me – is so complicated that I am usually happy when it works at all (after several days of fighting the settings).

**Comment by rikhuijzer** [comment] 2023-01-06 16:04
> But the notebooks also run locally if I delete the cache and run them again. Hm.

That makes no sense. This sounds like a bug, but this situation is also tested in https://github.com/rikhuijzer/PlutoStaticHTML.jl/blob/218a1625e7fcf6740c9411c4e4ba4b8ca634e5c0/test/cache.jl#L85-L88

Specifically, the test verifies that a notebook runs if the output file is removed.

> The docs-project.toml will not have Manopt in its dependencies (it never had) and locally here that would mean I would have to ask somewhere for the dev version? I will have to check for that.

When using Pluto with `use_distributed=true`, the docs-project.toml should have no influence on Pluto's evaluation. You can see the difference at https://github.com/fonsp/Pluto.jl/blob/febc398cafc9f3901a7f001759323eb13e23f8fe/src/evaluation/WorkspaceManager.jl#L61-L76. Without `use_distributed`, the evaluation happens in the local process. With `use_distribution`, a completely new Julia process is started. That's also why `use_distributed=true` allows for completely parallel evaluation of notebooks.

**Comment by rikhuijzer** [comment] 2023-01-06 16:05
> With the docs directory I am not yet so sure it will work, at least not consistently between local and CI for a simple reason:
The docs-project.toml will not have Manopt in its dependencies (it never had) and locally here that would mean I would have to ask somewhere for the dev version? I will have to check for that.

Yes that should work via `Pkg.develop(; path=<path/to/Manopt.jl>)`.

**Comment by kellertuer** [comment] 2023-01-06 16:14
> > But the notebooks also run locally if I delete the cache and run them again. Hm.
> 
> That makes no sense. This sounds like a bug, but this situation is also tested in

Maybe, as I said, I completely lost time on this issue as I usually do with PlutoStaticHTML, since this overall is a very complex thing and I am usually happy if it just works. So to be honest: Currently locally it just uses _some_ cache – I am not even sure where that is, but it is nice, if one reworks the docs, so I also did not try to change that for today (yet).
But what is cool is that it seems to even check for a manually written out md-file (that was what I was surprised about).

> > The docs-project.toml will not have Manopt in its dependencies (it never had) and locally here that would mean I would have to ask somewhere for the dev version? I will have to check for that.
> 
> When using Pluto with `use_distributed=true`, the docs-project.toml should have no influence on Pluto's evaluation. You can see the difference at https://github.com/fonsp/Pluto.jl/blob/febc398cafc9f3901a7f001759323eb13e23f8fe/src/evaluation/WorkspaceManager.jl#L61-L76. Without `use_distributed`, the evaluation happens in the local process. With `use_distribution`, a completely new Julia process is started. That's also why `use_distributed=true` allows for completely parallel evaluation of notebooks.

I have not yet tried the parallel evaluation, but will start a `ManoptExamples` soon to try that (where status will always display which versions the examples are done with). 


Thanks for the hint with `Pkg.develop` – will try to use that next and hope to get something that is consistent between local and CI runs.

**Comment by kellertuer** [comment] 2023-01-06 18:00
I just wanted to start this and noticed another problem: The user should also be able to run the notebook, but they do not have Manopt locally, so then the `Pkg.develop` will not work, right? I fear this stays an impossible scenario.

**Comment by kellertuer** [comment] 2023-01-06 20:06
It took a while, for now I ended up with something like

```julia
begin
	Pkg.activate(; temp=true)
    packages = [
  		PackageSpec(; name="Manifolds", version="0.8"),
   		PackageSpec(; name="Colors", version="0.12"),
   		PackageSpec(; name="PlutoUI", version="0.7"),
	]
	manopt_pkg = PackageSpec(; name="Manopt", version="0.3.51")
	if nb_mode === :develop || nb_mode === :auto
		curr_folder = pwd()
		parent_folder = dirname(curr_folder)
		manopt_file = joinpath(parent_folder,"src","Manopt.jl")
		if endswith(curr_folder,"tutorials") && isfile(manopt_file)
			# Manopt in dev mode
			Pkg.develop(path=parent_folder)
			nb_dev = true
		else
			nb_dev = false
			push!(packages, manopt_pkg)
			if nb_mode === :develop
				error("Development mode not possible, we are either not in the `tutorials/` folder or in `../src/` there is no `Manopt.jl` file,");
			end
		end
	else
		nb_dev = false
		push!(packages, manopt_pkg)
	end
	Pkg.add(packages)
end;
```

where the only litte sad thing is that if `nb_mode = :tutorial` this cell (in Pluto) has quite some terminal output that I would like to optionally hide.
In the saved notebook this ends up at the end, which I think is wrong – but I have to check, because that might be due to `nb_mode` being a symbol from a dropdown bind at the end.

**Comment by kellertuer** [comment] 2023-01-06 20:20
As one can see here

https://github.com/JuliaManifolds/Manopt.jl/actions/runs/3857173871/jobs/6574264402#step:4:922

This still fails on CI (runs fine locally again),
though `nb_mode` is `:auto`

Also locally all `# hideall` cells (for example the binder) are still shown – not sure why, because I thought it would hide cells.

**Comment by kellertuer** [comment] 2023-01-06 21:45
and a last iteration for today, I am back to where I ended up before starting reworking

* works locally (with the little strange outputs as mentioned above) – and no not with caching, it really runs the notebook
* does not work on CI now claiming `nb_mode` so somehow on CI the cells are now evaluated in the wrong order?!

Maybe I should consider just going back to Markdown files. The 4 days that I now spent debugging, I could have written more tutorials besides rewriting the current ones in Markdown. I am not sure anymore it's worth all this random guessing of stuff that might maybe work.

Its probably not only that the topic per se is quite complicated – probably I am also just too stupid for PlutoStaticHTML.

**Comment by kellertuer** [comment] 2023-01-07 10:25
I would have switched back to Markdown today, but I saw a post on Tulip this morning and gave that a try. With

```Julia

# ╔═╡ a3c81cc3-02a9-41cd-8eb7-3d665d42c024
# hideall
_nb_mode = :auto;

# ╔═╡ b198b15d-e547-47f7-a274-9ca0bc2331d6
# hideall
begin
	if _nb_mode === :auto || _nb_mode === :development
		import Pkg
		curr_folder = pwd()
		parent_folder = dirname(curr_folder)
		manopt_file = joinpath(parent_folder,"src","Manopt.jl")
		# the tutorial is still in the package and not standalone
		_in_package =  endswith(curr_folder,"tutorials") && isfile(manopt_file)
		if _in_package
			eval(:(Pkg.develop(path=parent_folder)))  # directory of MyPkg
		end
	else
		_in_package = false
	end;
	using Manopt, Manifolds, Random, Colors, PlutoUI
end
```

It works – if we are in the package and the total is not standalone, we take Manopt into development mode (but even _keep_ Plutos package manager). The only small change necessary is – if there is a breaking update for Manopt, to adapt the compat entry to the new version. For the first 3 notebooks this works, even that it loads the old version if one sets `_nb_mode = :tutorial`.
