### ISSUE TITLE
HTML file doesn't capture standard output

### ISSUE THREAD

**Issue by MarkNahabedian** [rikhuijzer/PlutoStaticHTML.jl#155] opened 2022-11-16 22:01 UTC
Pluto notebooks now show text sent to standard output, for example, from `println`.  PlutoStaticHTML is apparently not including this in HTML output though.

**Comment by rikhuijzer** [comment] 2022-11-17 07:05
Hi Mark and thanks for your interest in this project.

This issue is a duplicate of #104. My current idea with this project is that the static HTML output should be reasonably polished. For example, I'm using PlutoStaticHTML for my blog (e.g., https://huijzer.xyz/posts/shapley/) and it's used for documentation (e.g., https://manoptjl.org/stable/tutorials/AutomaticDifferentiation/). Showing `stdout` and `stderr` would be a distraction. You can still explicitly obtain these outputs via [`IOCapture.jl`](https://github.com/JuliaDocs/IOCapture.jl).

For example:

```julia
using IOCapture
```

```julia
begin
    c = IOCapture.capture() do
        println("test")
    end
    c.output
end
```

> test

Or, to get rid of all the `IOCapture`, one can use `# hide` comments:

```julia
begin # hide
    c = IOCapture.capture() do # hide
println("test")
    end # hide
    c.output # hide
end # hide
```

> test

which will appear as
```julia
println("test")
```

> test

**Closed by rikhuijzer** 2022-11-17 07:05 UTC

**Comment by MarkNahabedian** [comment] 2022-11-17 12:49
Rik, thanks for your quick response.

My notebook uses `println` to inform the user, as any program would.

Perhaps there should be an option to control whether the HTML should include `stdout`.
